theme: jekyll-theme-cayman
title: 欢迎来到 IXBOB 的个人博客
description: 这里用来放置Minecraft地图（烂的，破的，不要钱的，正在更新的）

<iframe src="https://onedrive.live.com/embed?cid=BC563DD7E78B8181&resid=BC563DD7E78B8181%216655&authkey=AAa2IGmffsOzAPk" width="165" height="128" frameborder="0" scrolling="no"></iframe>
