tag @s remove set.start.players.2
tag @s remove set.start.players.3
tag @s remove set.start.players.5
tag @s remove set.start.players.6
tag @s remove set.start.players.7
tag @s remove set.start.players.8
tag @s remove have.set.start.players.2
tag @s remove have.set.start.players.3
tag @s remove have.set.start.players.5
tag @s remove have.set.start.players.6
tag @s remove have.set.start.players.7
tag @s remove have.set.start.players.8
tag @s add have.set.start.players.4