execute @s[type=armor_stand,scores={"开始倒计时"=20},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 20秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=19},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 19秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=18},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 18秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=17},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 17秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=16},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 16秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=15},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 15秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=14},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 14秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=13},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 13秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=12},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 12秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=11},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 11秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=10},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 10秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=9},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 9秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=8},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 8秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=7},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 7秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=6},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 6秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=5},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 5秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=4},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 4秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=3},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 3秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=2},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 2秒" "等待显示" -5
execute @s[type=armor_stand,scores={"开始倒计时"=1},tag=reset_OK] ~~~ scoreboard players set "游戏开始： 1秒" "等待显示" -5