#红保护
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:red_team_helmet_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:red_team_chestplate_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:red_team_leggings_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:red_team_boots_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:red_team_helmet_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:red_team_chestplate_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:red_team_leggings_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:red_team_boots_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:red_team_helmet_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:red_team_chestplate_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:red_team_leggings_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:red_team_boots_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=1,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
#蓝保护
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:blue_team_helmet_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:blue_team_chestplate_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:blue_team_leggings_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:blue_team_boots_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=1}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectioni 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:blue_team_helmet_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:blue_team_chestplate_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:blue_team_leggings_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:blue_team_boots_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=2}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectionii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.head 0 bedwars:blue_team_helmet_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.chest 0 bedwars:blue_team_chestplate_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:blue_team_leggings_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:blue_team_boots_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:chainmail_leggings_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:chainmail_boots_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:iron_leggings_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:iron_boots_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.legs 0 bedwars:diamond_leggings_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝保护等级"=3}] ~~~ replaceitem entity @a[scores={"分队"=2,"防具等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126] slot.armor.feet 0 bedwars:diamond_boots_protectioniii 1 0 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}
#红锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ clear @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ clear @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ clear @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ clear @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ give @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] bedwars:wooden_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}} 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ give @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] bedwars:stone_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ give @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] bedwars:iron_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ give @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] bedwars:diamond_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=1}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ clear @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ clear @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ clear @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ clear @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ give @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:wooden_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}} 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ give @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:stone_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ give @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:iron_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ give @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:diamond_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=2}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ clear @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ clear @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ clear @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ clear @a[scores={"分队"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ give @a[scores={"分队"=1,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:wooden_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}} 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ give @a[scores={"分队"=1,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:stone_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ give @a[scores={"分队"=1,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:iron_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ give @a[scores={"分队"=1,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:diamond_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"红锋利等级"=3}] ~~~ tag @a[scores={"分队"=1}] add have_upgraded_sword_sharpnessIII
#蓝锋利
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ clear @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] wooden_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ clear @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] stone_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ clear @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] iron_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ clear @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] diamond_sword
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ give @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] bedwars:wooden_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}} 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ give @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] bedwars:stone_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ give @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] bedwars:iron_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ give @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessI] bedwars:diamond_sword_sharpnessI 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=1}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ clear @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:wooden_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ clear @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:stone_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ clear @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:iron_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ clear @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:diamond_sword_sharpnessI
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ give @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:wooden_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}} 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ give @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:stone_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ give @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:iron_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ give @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessII] bedwars:diamond_sword_sharpnessII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=2}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ clear @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:wooden_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ clear @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:stone_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ clear @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:iron_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ clear @a[scores={"分队"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:diamond_sword_sharpnessII
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ give @a[scores={"分队"=2,"剑等级"=1},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:wooden_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}} 
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ give @a[scores={"分队"=2,"剑等级"=2},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:stone_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ give @a[scores={"分队"=2,"剑等级"=3},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:iron_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ give @a[scores={"分队"=2,"剑等级"=4},x=-63,y=171,z=-63,dx=126,dy=33,dz=126,tag=!have_upgraded_sword_sharpnessIII] bedwars:diamond_sword_sharpnessIII 1 0 {"minecraft:item_lock":{"mode":"lock_in_inventory"},"minecraft:keep_on_death":{}}
execute @e[type=armor_stand,name=main,scores={gameSTART=1,"蓝锋利等级"=3}] ~~~ tag @a[scores={"分队"=2}] add have_upgraded_sword_sharpnessIII
